### PR TITLE
Part3

### PR DESCRIPTION
**Pull request by Junochop**
contactService.js error is showing.

### CODE REVIEW

**Comment by rousell** [comment]
This is a resource for validation: https://scotch.io/tutorials/angularjs-form-validation

**Comment by Junochop** [comment]
please check my updated submit function.

**Comment by zoeames** [comment]
The validation is still not correct.  It tells me that a field is not valid but still allows me to click the submit button

**Comment by Junochop** [comment]
deployed to the firebase.  It works as expected.

**Comment by rousell** [comment]
👍  just checked the deployed project and the submit button is disabling as expected. merging in

**Pull request merged**
